name: Go Build & Format
on:
  push:
    tags-ignore:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - run: go version
    - uses: actions/checkout@v1
    - run: go fmt .
    - run: go build -v .
